# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b01d30129f13abc80fec34b069fbd0e008b70e2433a6e5264195d656ee74377e78e85cd77601c1fce9beb9deddf92138a695d4d5d1f02e114aa9abfcb14987

test:
  secret_key_base: 282c2a6a4256d9bb4d2369cd09ad43c36e284d3d278008b97d21db48bc86f80f5f8adf79377db04704ae207dfd26f3fd756ee0c4af463a6212a943b42e8544f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
